// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Sat Sep 28 21:57:38 2024

7_seg_driver 7_seg_driver_inst
(
	.D0(D0_sig) ,	// input  D0_sig
	.D1(D1_sig) ,	// input  D1_sig
	.D2(D2_sig) ,	// input  D2_sig
	.D3(D3_sig) ,	// input  D3_sig
	.Ripple_Blanking(Ripple_Blanking_sig) ,	// input  Ripple_Blanking_sig
	.Seg_0(Seg_0_sig) ,	// output  Seg_0_sig
	.Seg_1(Seg_1_sig) ,	// output  Seg_1_sig
	.Seg_2(Seg_2_sig) ,	// output  Seg_2_sig
	.Seg_3(Seg_3_sig) ,	// output  Seg_3_sig
	.Seg_4(Seg_4_sig) ,	// output  Seg_4_sig
	.Seg_5(Seg_5_sig) ,	// output  Seg_5_sig
	.Seg_6(Seg_6_sig) ,	// output  Seg_6_sig
	.Ripple_Blanking_Carry(Ripple_Blanking_Carry_sig) 	// output  Ripple_Blanking_Carry_sig
);

